### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by TomasTomecek** [container-images/nodejs#1]
@kasicka 
Since you didn't create a PR, this is my feedback:

 * Remove the template README and provide real one:
   * what is this, how to build it, how to run it, what's inside
 * Clarify that OpenShift template is not filled yet
 * Remove template files (e.g. Dockerfile.template)
 * https://github.com/container-images/nodejs/blob/master/6/.nodejs.yaml.swp o_O
   * .gitignore ftw
 * Probably remove `Chrome` word from description since it's likely copyrighted, v8 should be just fine
 * you should coordinate with @mkocka on s2i-enabling the image
 * don't set version in modulemd, it is filled by build system - module version and rpm versions are not aligned
   * build requires and requires are for `module:stream`, not rpms, so leave there only base-runtime
   * profiles, api is okay
   * components should contain srpms (dist-git repo names), not binary rpms, so remove debuginfo and devel
   * and **most importantly**: figure out what packages does your package need for build:
     * check what is available in base runtime - if it's missing in there, write it down, we need to put it to some module
       * here is our awesome script to do that: https://pagure.io/modularity/modularity-tools/blob/master/f/brt_dep_solver.sh
    * do this recursively - so when you build require is missing, check what BR are needed to build it
    * it is also possible to disable features in your package for Boltron (e.g. systemtap probes, since it is really hard to build systemtap)
    * Try to build your module locally: https://docs.pagure.org/modularity/development/building-modules/building-local.html#option-2-docker-image-and-a-helper-script
 * Submit PR with the changes

**Comment by eliskasl** [comment]
Just a note that @mkocka is no longer working on languages; @rpitonak is your man regarding s2i-enabling NodeJS.

**Comment by rpitonak** [comment]
I think, we can close this one.
